version: '3.9'

services:
  node-api:
    build:
      context: ./backend/node
      dockerfile: Dockerfile
    container_name: finscope-node
    env_file:
      - ./.env
    environment:
      - PYTHON_SERVICE_URL=http://py-api:8000
    ports:
      - "4000:4000"
    depends_on:
      - py-api
    networks:
      - finscope-net

  py-api:
    build:
      context: ./backend/python
      dockerfile: Dockerfile
    container_name: finscope-python
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - finscope-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:4000}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_KEY: ${VITE_SUPABASE_KEY}
        VITE_AUTH_PROVIDER: ${VITE_AUTH_PROVIDER:-email}
        VITE_PY_API_BASE_URL: ${VITE_PY_API_BASE_URL:-http://localhost:8000}
    container_name: finscope-frontend
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    depends_on:
      - node-api
    networks:
      - finscope-net

networks:
  finscope-net:
    driver: bridge
