name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Node API image
        uses: docker/build-push-action@v6
        with:
          context: ./backend/node
          file: ./backend/node/Dockerfile
          push: false
          tags: finscope-node-api:ci

      - name: Build Python API image
        uses: docker/build-push-action@v6
        with:
          context: ./backend/python
          file: ./backend/python/Dockerfile
          push: false
          tags: finscope-py-api:ci

      - name: Build Frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          build-args: |
            VITE_API_BASE_URL=http://localhost:4000
            VITE_PY_API_BASE_URL=http://localhost:8000
            VITE_AUTH_PROVIDER=email
          tags: finscope-frontend:ci

      - name: Static check - frontend
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci --no-fund --no-audit
      - name: Frontend build (sanity)
        working-directory: frontend
        run: npm run build

      - name: Finish
        run: echo "Builds completed"
